language: java
jdk:
  - openjdk8
# before_script:
install: cd nuoquan-dev && mvn install -DskipTests=true -Dmaven.javadoc.skip=true

script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
